In [12]:
xs = []
ys = []

with open('img6.pattern', 'r') as f:
    for i, line in enumerate(f):
        if i == 0:
            print(line)
            continue
        x, y = [int(i) for i in line.strip().split()]
        xs.append(x)
        ys.append(y)

optimum=30



In [13]:
def get_cover(cx, cy, xs, ys, mask):
    return [(cx - x)**2 + (cy - y)**2 <= 16 and not exclude for x, y, exclude in zip(xs, ys, mask)]

def evaluate(a, b, xs, ys):
    m1 = get_cover(*a, xs, ys, [0]*40)
    m2 = get_cover(*b, xs, ys, m1)
    return sum(m1) + sum(m2)

In [14]:
maxcount = 0
argmax = None
for cy in range(2, 14):
    for cx in range(2, 14):
        mask = get_cover(cx, cy, xs, ys, [0]*40)
        if sum(mask) > maxcount:
            maxcount = sum(mask)
            maxmask = mask
            argmax = cx, cy
print(argmax, maxcount)

ca = argmax
cb = None
it = 0
while True:
    prevmask = maxmask
    maxmask = None
    maxcount = 0
    argmax = None
    for cy in range(2, 14):
        for cx in range(2, 14):
            mask = get_cover(cx, cy, xs, ys, prevmask)
            if sum(mask) >= maxcount:
                maxcount = sum(mask)
                maxmask = get_cover(cx, cy, xs, ys, [0]*40)
                argmax = cx, cy
    if (ca, argmax) == (ca, cb):
        print('break first')
        break
    cb = argmax
    print(argmax, maxcount, [ca, cb], evaluate(ca, cb, xs, ys))

    prevmask = maxmask
    maxmask = None
    maxcount = 0
    argmax = None
    for cy in range(2, 14):
        for cx in range(2, 14):
            mask = get_cover(cx, cy, xs, ys, prevmask)
            if sum(mask) >= maxcount:
                maxcount = sum(mask)
                maxmask = get_cover(cx, cy, xs, ys, [0]*40)
                argmax = cx, cy
    # print(argmax, ca, cb, sum(get_cover(*argmax, xs, ys, prevmask)))
    if (argmax, cb) == (ca, cb):
        print('break second')
        break
    ca = argmax
    print(argmax, maxcount, [ca, cb], evaluate(ca, cb, xs, ys))
    it += 1
    if it > 10:
        break

(9, 6) 22
(13, 3) 7 [(9, 6), (13, 3)] 29
(9, 9) 18 [(9, 9), (13, 3)] 29
(13, 2) 12 [(9, 9), (13, 2)] 30
break second


In [145]:
m2 = get_cover(10, 8, xs, ys, [0]*40)
np.array(m2).astype(np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [149]:
m1 = get_cover(9, 6, xs, ys, [0]*40)
m2 = get_cover(10, 8, xs, ys, m1)

print(sum(m1), sum(m2))

22 2


In [148]:
np.array(m2).astype(np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [150]:
np.array(m1).astype(np.int32)

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [41]:
m1[23], xs[23], ys[23]

(True, 7, 11)

In [119]:
xs = []
ys = []
for x in range(16):
    for y in range(16):
        xs.append(x)
        ys.append(y)


In [123]:
covers = {}
for x in range(8):
    for y in range(8):
        covers[x, y] = np.array(get_cover(x, y, xs, ys, [0]*len(xs)))

In [130]:
def find(x, y):
    cur = covers[x, y]
    for px in range(x):
        for py in range(y):
            pcur = covers[px, py]
            if not ((cur & pcur) == pcur).all():
                with np.printoptions(linewidth=10000, formatter={'bool': lambda x : str(int(x))}):
                    print(cur)
                    print(pcur)
                    print((cur & pcur))
                return False
    return True


# for x in range(8):
#     for y in range(8):
#         if find(x, y):
#             print(x, y)

In [132]:
find(2, 2)

True

In [138]:
sum(covers[0, 0])

17